### ISSUE TITLE
Invalid syntax

### ISSUE THREAD

**Issue by DavidVentura** [chdemko/pandoc-latex-fontsize#2]
Hi,
I copied the example to my header

```
---
title: "some title"
pandoc-latex-fontsize:
    - classes: [smallcontent]
    size: tiny
    - classes: [largecontent, important]
    size: huge
header-includes:
    - \usetheme{Madrid}
    - \usecolortheme{lily}
    - \usefonttheme{professionalfonts}
---

```

and when running

```
pandoc -N -t beamer airflow.md --highlight-style=breezedark --filter pandoc-latex-fontsize -o airflow.pdf 
```

I get 
```
[pandoc warning] Could not parse YAML header: did not find expected '-' indicator "source" (line 6, column 5)
```
(Line 6 being the second `- classes`)

and I don't see this working on my pdf output (size doesn't change), example:

```{.yaml .smallcontent}
30 01 download.yml
30 01 download.yml
30 01 download.yml
```

is the same with and without `.smallcontent`.
